import 'package:piloto_drinks/enums/ingredient_enum.dart';
import 'package:piloto_drinks/enums/method_prepare_enum.dart';
import 'package:piloto_drinks/types/ingredient_type.dart';
import 'package:piloto_drinks/types/revenue_type.dart';

List<Revenue> drinksData = [
  Revenue(
    'Maeves Misxology',
    'Vodka',
    MethodPrepareEnum.mounted,
    [
      Ingredient(IngredientEnum.vodka, '50ml'),
      Ingredient(IngredientEnum.purePessego, '50ml'),
      Ingredient(IngredientEnum.scLaranja, '50ml'),
      Ingredient(IngredientEnum.xpGengibre, '20ml'),
      Ingredient(IngredientEnum.mel, '25ml'),
      Ingredient(IngredientEnum.xpAcucar, '25ml'),
    ],
    'Misturar todos os ingredientes em um copo (400ml) com gelo e servir com o canudo',
    garnish: 'Canudo de piroka',
  ),
  Revenue(
    'Elemento X',
    'Vodka e Fireball',
    MethodPrepareEnum.mounted,
    [
      Ingredient(IngredientEnum.carvao, '1 bailarina'),
      Ingredient(IngredientEnum.vodka, '25ml'),
      Ingredient(IngredientEnum.fireball, '50ml'),
      Ingredient(IngredientEnum.scLimaoTaiti, '30ml'),
      Ingredient(IngredientEnum.xpAbacaxi, '30ml'),
      Ingredient(IngredientEnum.scLimaoSiciliano, '30ml'),
      Ingredient(IngredientEnum.scLaranja, 'Completar'),
    ],
    'Dissolver o carvão na vodka, misturar todos os ingredientes em um copo (400ml) com gelo e servir',
    garnish: 'X branco no copo',
  ),
  Revenue(
      'Cerveja amanteigada',
      'Chopp',
      MethodPrepareEnum.smoothie,
      [
        Ingredient(IngredientEnum.xpBaunilha, '50ml'),
        Ingredient(IngredientEnum.sorveteCreme, '1/2 bola'),
        Ingredient(IngredientEnum.manteiga, '1 bailarina'),
        Ingredient(IngredientEnum.bitterEspeciarias, '10ml'),
        Ingredient(IngredientEnum.chopp, 'Completar'),
      ],
      'Bater tudo na coqueteira com a mola do Strainer, colocar no copo (500ml) e completar com Chopp'),
  Revenue(
      'Barbie Shake',
      'Vodka',
      MethodPrepareEnum.blender,
      [
        Ingredient(IngredientEnum.vodka, '75ml'),
        Ingredient(IngredientEnum.leite, '100ml'),
        Ingredient(IngredientEnum.corRosa, '1 bailarina'),
        Ingredient(IngredientEnum.morango, '6un.'),
        Ingredient(IngredientEnum.xpFrutasVermelhas, '50ml'),
        Ingredient(IngredientEnum.sorveteCreme, '1 bola  1/2'),
      ],
      'Bater todos os ingredientes no liquidificador, servir em um copo (400ml) e decorar',
      garnish: 'Chantilly com confeitos'),
  Revenue(
      'Pandora',
      'Gin',
      MethodPrepareEnum.smoothie,
      [
        Ingredient(IngredientEnum.gin, '50ml'),
        Ingredient(IngredientEnum.xpAbacaxi, '50ml'),
        Ingredient(IngredientEnum.scLimaoTaiti, '25ml'),
        Ingredient(IngredientEnum.scLimaoSiciliano, '25ml'),
        Ingredient(IngredientEnum.xpCardamomo, '25ml'),
      ],
      'Bater todos os ingredientes, servir em um copo (400ml) e finalizar com a espuma de gengibre',
      garnish: 'Espuma de Gengibre'),
  Revenue(
      'Page Cardio',
      'Gin',
      MethodPrepareEnum.mounted,
      [
        Ingredient(IngredientEnum.gin, '50ml'),
        Ingredient(IngredientEnum.scLimaoSiciliano, '50ml'),
        Ingredient(IngredientEnum.aguaTonica, 'Completar'),
      ],
      'Misturar todos os ingredientes em um copo (400ml) com gelo, decorar e servir',
      garnish: 'Seringa de Xarope de frutas vermelhas'),
  Revenue(
      'Wonka',
      'Vodka e Licor de chocolate',
      MethodPrepareEnum.blender,
      [
        Ingredient(IngredientEnum.vodka, '50ml'),
        Ingredient(IngredientEnum.licChocolate, '50ml'),
        Ingredient(IngredientEnum.leite, '100ml'),
        Ingredient(IngredientEnum.xpBaunilha, '25ml'),
        Ingredient(IngredientEnum.clChocolate, 'Olho'),
        Ingredient(IngredientEnum.sorveteCreme, '1 bola  1/2'),
      ],
      'Bater todos os ingredientes no liquidificador, servir em um copo (400ml) e decorar',
      garnish: 'Chantilly com calda de chocolate'),
  Revenue(
      'Ghostface',
      'Rum',
      MethodPrepareEnum.mounted,
      [
        Ingredient(IngredientEnum.cereja, '2un.'),
        Ingredient(IngredientEnum.rum, '50ml'),
        Ingredient(IngredientEnum.clCereja, '12ml'),
        Ingredient(IngredientEnum.scLimaoTaiti, '2un.'),
        Ingredient(IngredientEnum.pimentaTabasco, '1 gota'),
        Ingredient(IngredientEnum.monsterPacificPunch, 'Completar'),
      ],
      'Macerar as cerejas, completar o copo (400ml) com gelo, misturar os ingredientes, decorar com a espuma de gengibre e fechar com plastico',
      garnish: 'Espuma de gengibre, plastico e canudo cortado'),
  Revenue(
      'Manopla do infinito',
      'Gin',
      MethodPrepareEnum.smoothie,
      [
        Ingredient(IngredientEnum.gin, '50ml'),
        Ingredient(IngredientEnum.scLaranja, '50ml'),
        Ingredient(IngredientEnum.scLimaoTaiti, '25ml'),
        Ingredient(IngredientEnum.xpTangerina, '25ml'),
        Ingredient(IngredientEnum.corDourado, '1 bailarina'),
        Ingredient(IngredientEnum.monsterKhaotic, 'Completar'),
      ],
      'Bater todos os ingredientes, servir em um copo (400ml) e finalizar com as jujubas no palito',
      garnish: 'Corante dourado e jujubas no palito'),
  Revenue(
      'Let it go',
      'Tequila e Triple Sec',
      MethodPrepareEnum.blender,
      [
        Ingredient(IngredientEnum.tequila, '75ml'),
        Ingredient(IngredientEnum.tripleSec, '15ml'),
        Ingredient(IngredientEnum.scLimaoTaiti, '25ml'),
        Ingredient(IngredientEnum.curacauBlue, '25ml'),
      ],
      'Bater todos os ingredientes no liquidificador adicionando gelo aos poucos até dar o ponto de raspadinha e servir em um copo (400ml) com borda de limão com sal'),
  Revenue(
      'Central Perk',
      'Vodka e Licor de café',
      MethodPrepareEnum.blender,
      [
        Ingredient(IngredientEnum.vodka, '50ml'),
        Ingredient(IngredientEnum.licChocolate, '50ml'),
        Ingredient(IngredientEnum.leite, '100ml'),
        Ingredient(IngredientEnum.xpBaunilha, '25ml'),
        Ingredient(IngredientEnum.carvao, '1 bailarina'),
        Ingredient(IngredientEnum.sorveteCreme, '1 bola  1/2'),
      ],
      'Bater todos os ingredientes no liquidificador, servir em um copo (400ml) e decorar',
      garnish: 'Chantilly e grãos de café'),
  Revenue(
      'Morningstart',
      'Gin',
      MethodPrepareEnum.mounted,
      [
        Ingredient(IngredientEnum.gin, '50ml'),
        Ingredient(IngredientEnum.shrubMorangoAlecrim, '75ml'),
        Ingredient(IngredientEnum.pimentaTabasco, '3 gotas'),
        Ingredient(IngredientEnum.scLimaoTaiti, '25ml'),
        Ingredient(IngredientEnum.xpAcucar, '25ml'),
        Ingredient(IngredientEnum.aguaTonica, 'Completar'),
      ],
      'Misturar todos os ingredientes em um copo (400ml) com gelo, decorar e servir',
      garnish: 'Pimentas'),
  Revenue(
      'Tributo Voraz',
      'Vodka e Licor de pêssego',
      MethodPrepareEnum.mounted,
      [
        Ingredient(IngredientEnum.vodka, '50ml'),
        Ingredient(IngredientEnum.licPessego, '25ml'),
        Ingredient(IngredientEnum.scLaranja, 'Completar'),
      ],
      'Misturar todos os ingredientes em um copo (400ml) com gelo, finalizar com Grenadine e servir',
      garnish: 'Grenadine'),
  Revenue(
      'Yoda\'s Elixir',
      'Sake e Licor de Maça verde',
      MethodPrepareEnum.mounted,
      [
        Ingredient(IngredientEnum.sake, '50ml'),
        Ingredient(IngredientEnum.licMacaVerde, '50ml'),
        Ingredient(IngredientEnum.scLimaoTaiti, '25ml'),
        Ingredient(IngredientEnum.xpGengibre, '25ml'),
        Ingredient(IngredientEnum.xpCampimSanto, '50ml'),
        Ingredient(IngredientEnum.monsterUltraParadise, 'Completar'),
      ],
      'Misturar todos os ingredientes em um copo (400ml) com gelo, decorar e servir',
      garnish: 'Pacote de pão e orelhas de limão'),
];
